### ISSUE TITLE
Window is not available on static site generators.

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro-viz#123]
## Description

I am running the `KedroViz` react component inside of a gatsby application.  When doing so I get an error that window is not available.  To resolve this I need to implement a `componentDidMount` method, and only render `KedroViz` after the component did mount.

Is it possible to **check if window is available before using it**?  The Error came from [config.js#L7](https://github.com/quantumblacklabs/kedro-viz/blob/807c68c52cc7fdf69a845e0b769bdcccea397a39/src/config.js#L7), appears to me that it could check for window before using it.

## Context

I am running KedroViz `3.2.0`, I believe that this is in all versions, and is not related to the new release.

📈 [Running Site](https://default-kedro-157.waylonwalker.com/)

👨‍💻  [index.js](https://github.com/WaylonWalker/default-kedro157/blob/master/gatsby-kedro-viz/src/pages/index.js)

## Actual Result

The error occurred in [config.js#L7](https://github.com/quantumblacklabs/kedro-viz/blob/807c68c52cc7fdf69a845e0b769bdcccea397a39/src/config.js#L7).  Without understanding `KedroViz` further I cannot say that it would not error on other windows.  I do see 8 instances of window just by searching the repo.

## 👏 Thanks

Thanks for open sourcing everything and making such an amazing set of tools!!

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by WaylonWalker** [comment]
I just realized that the latest version is not working even behind a `componentDidMount`, Rolling back to `3.0.1` seems to resolve the issue.

**Comment by richardwestenra** [comment]
Hey @WaylonWalker  thanks for this! I think I've figured out where it's coming from:

It's all the various window declarations in config and components, but also the ones in the `svg-crowbar` dependency that was introduced in 3.1.0. I've got a patch PR that I'm working on, but in the meantime here's a quick fix for your build and any other affected gatsby sites:

Replace your regular import:
```
import KedroViz from "@quantumblack/kedro-viz"
```
with a conditional import like this:
```
const KedroViz = typeof window !== 'undefined' ? require('@quantumblack/kedro-viz').default : () => null;
```

I've tested this on a gatsby site and it seems to work. This means that KedroViz won't be included in the static HTML build, it's only added on the client.

**Comment by WaylonWalker** [comment]
Great, Thanks @richardwestenra!  That works for me.  Hopefully, it will be possible to get into the static build in the future.  I didn't even think to conditionally import.

**Comment by richardwestenra** [comment]
Cheers! I'm actually going to reopen this issue because I think it's worth fixing properly. I'll contact the maintainer of `svg-crowbar` and see whether they can patch that code too.

**Comment by richardwestenra** [comment]
@WaylonWalker this should now be fixed on the `develop` branch, and will be fixed in the upcoming release.
