### ISSUE TITLE
Dependency conflict with commonly used AWS libraries

### ISSUE THREAD

**Issue by chriswynnyk** [quantumblacklabs/kedro-viz#13]
## Description
Dependency conflict with PyYAML.
Kedro requires PyYAML>=5.1, <6.0 while various AWS libraries require in the range PyYAML<4.3,>=3.10.

This is the same issue encountered here: https://github.com/quantumblacklabs/kedro/issues/36

Looking to relax the requirements here:
https://github.com/quantumblacklabs/kedro-viz/blob/develop/package/test_requirements.txt

## Context
I'm unable to visualize my project, with the error:
![Screen Shot 2019-07-12 at 5 28 50 PM](https://user-images.githubusercontent.com/3810469/61159837-60271080-a4cb-11e9-9f77-dfd5bd00dbc3.png)
 
## Steps to Reproduce

- `pip install kedro sagemaker kedro-viz`
- `kedro viz`

## Expected Result

This should launch the kedro viz.

## Actual Result

Fails when checking dependencies, see error above.

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Kedro version used (pip show kedro or kedro -V): 0.14.3
* Python version used (python -V): 3.7.3
* Operating system and version: macOS Mojave 10.14.5

## Checklist
- [x] Include labels so that we can categorize your issue

**Comment by tolomea** [comment]
The next version of Kedro will loosen the requirement on PyYAML to >=4.2.
Will that fix the problem? or am I missing some additional detail?

**Comment by yetudada** [comment]
Hi @chriswynnyk! I just realised we forgot to close this issue. Current pinning for `PyYAML>=4.2, <6.0` in `kedro`.

And hang on, I just realised, you made a `kedro sagemaker` plugin? 🎉

**Comment by yetudada** [comment]
@chriswynnyk We're working with the AWS team to produce a knowledge document on using Kedro and Sagemaker. Would we be able to talk to you about how you used them together?
