### ISSUE TITLE
[KED-1487] kedro-viz does not open the given host (simple fix)

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro-viz#131]
## Description

I was browsing through the implementation of the viz server and noticed that the host variable from the cli does not get passed to webbrowser on line 347.  

[kedro_viz/server.py#L347](https://github.com/quantumblacklabs/kedro-viz/blob/develop/package/kedro_viz/server.py#L347)

**Comment by 921kiyo** [comment]
Hi @WaylonWalker thank you for reporting! We will log this and fix it later :)

**Comment by lorenabalan** [comment]
Thanks Waylon, this is now fixed! It was actually intended behaviour, but you're right that it wasn't easy to tell from the code. Hoping now it's a bit clearer!
