### ISSUE TITLE
Zoom Accessibility

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro-viz#140]
I have a teammate without a scroll wheel that was not able navigate a large viz.  Would it be possible to add buttons, or some other UI element to control the zoom?

**Comment by yetudada** [comment]
It's coming! We have a new mini-map feature that we're working on. Which is going to make it awesome to navigate large pipeline visualisation.

**Comment by yetudada** [comment]
![minimap](https://user-images.githubusercontent.com/43755008/78263934-7b72f980-74fa-11ea-8975-13815544f4fa.gif)

Would something like this help? This is a super early Sketch prototype of it. It has not been built yet.

**Comment by WaylonWalker** [comment]
Yes it would help.  I like it!  


I would say though, as someone looking for a zoom button for the first time, the map icon isn't necessarily intuitive as the +/- buttons.  If there is enough space for all four icons could it display all four, and expand the map when clicking map.  I would hate to see too much clutter in the UI.  Maybe its possible to collapse those, but default to open.  That way the user will know they are there before they collapse the four buttons.

**Comment by yetudada** [comment]
Aww yes 😄! This is great feedback. Let me get these thoughts over to @GabrielComymQB, our superstar Designer.

**Comment by GabrielComymQB** [comment]
Thanks for the insights!  Stay tuned for more :) Loads of delightful interactions coming very soon

**Comment by richardwestenra** [comment]
Thanks for posting this @WaylonWalker, good catch. As Yetu and Gabriel said, we've got this coming in a future version, but as a short term fix, please let your colleague know that they can zoom in by double-clicking on the chart, and zoom out by holding shift while double-clicking. This feature is built into d3-zoom :)
