### ISSUE TITLE
Kedro viz breaks when Kedro Project has Pyspark Context

### ISSUE THREAD

**Issue by dpavancini** [quantumblacklabs/kedro-viz#160]
## Description
When I run kedro viz in a project with SparkContext an error occurs and no graph is shown. 

## Steps to Reproduce

1. Run Kedro Viz
2. Error occurs

## Expected Result
We should view the output of the Kedro Viz command on the browser

## Actual Result

![image](https://user-images.githubusercontent.com/13836121/81208816-0174db00-8fa6-11ea-9aa4-dcae64d7e0ef.png)

## Your Environment
Running on:
Python 3.6.9

* Operating system and version:
![image](https://user-images.githubusercontent.com/13836121/81209031-531d6580-8fa6-11ea-8f22-7d401cc0b608.png)
* Kedro version used (if relevant):
kedro==0.15.9
kedro-viz==3.2.0
pyspark==2.4.5
* Python version used (if relevant):

## Checklist
- [Bug]

**Comment by limdauto** [comment]
@dpavancini : Could you post your `ProjectContext` where you instantiate the spark session please? If you are persisting the spark session object in `ProjectContext`, i.e. `self._spark_session = ...`, can you try removing that and see if it helps?

**Comment by 921kiyo** [comment]
I think it's related to https://github.com/quantumblacklabs/kedro/issues/351

**Comment by dpavancini** [comment]
It does indeed look like that issue. I apologize for that. Since it was just happening when I ran kedro viz I looked there not in the main Kedro repo. I'll try this new Spark session best practice. Thanks guys.

**Comment by 921kiyo** [comment]
No problem! I'm closing thisissue, but do let us know if you encounter further problems :)
