### ISSUE TITLE
Fix support for Python 3.8

### ISSUE THREAD

**Issue by fkromer** [quantumblacklabs/kedro-viz#175]
## Description

Installing `kedro-viz` under Python 3.8 is not possible.

## Context

[Python 3.8 support of `kedro` has been added recently.](https://github.com/quantumblacklabs/kedro/issues/124) `kedro-viz` does not support Python 3.8 yet: [`python_requires=">=3.6, <3.8",`](https://github.com/quantumblacklabs/kedro-viz/blob/develop/package/setup.py#L72)

## Steps to Reproduce

1. Install Python 3.8
2. Install kedro
3. Try to install kedro-viz

## Expected Result

Successful installation of `kedro-viz`.

## Actual Result

Installation aborts.

```
$ kedro --version
kedro, version 0.16.1
$ pip3 install --user kedro-viz
ERROR: Could not find a version that satisfies the requirement kedro-viz (from versions: none)
ERROR: No matching distribution found for kedro-viz
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Operating system and version: Ubuntu 20.04
* Kedro version used (if relevant): 0.16.1
* Python version used (if relevant): 3.8.2

**Comment by richardwestenra** [comment]
Thanks for raising this @fkromer! This will be resolved in #173 :)

We are hoping to merge this PR today, and to release the new version of Kedro-Viz with 3.8 support, ideally within the next 24 hours or so. Watch this space ;)

**Comment by 921kiyo** [comment]
Hi @fkromer I've just merged https://github.com/quantumblacklabs/kedro-viz/pull/173, so I'm closing this issue and the new Kedro-Viz release is on the way :)

**Comment by fkromer** [comment]
@921kiyo Thanks a lot!
