### ISSUE TITLE
No such command "viz" and customized datasets not found

### ISSUE THREAD

**Issue by zhangchi1** [quantumblacklabs/kedro-viz#183]
## Description
I upgraded my project to kedro=0.16.1. However, I'm not able to run `kedro viz`

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce

1. Run `kedro install` to install all requirements
2. Run `kedro viz`

## Error Message

```
Traceback (most recent call last):
  File "~/python3.6/site-packages/kedro/framework/cli/cli.py", line 586, in load_entry_points
    entry_point_commands.append(entry_point.load())
  File "~/python3.6/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "~/python3.6/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "~/python3.6/site-packages/kedro_viz/__init__.py", line 34, in <module>
    from kedro_viz.server import format_pipeline_data  # noqa
  File "~/python3.6/site-packages/kedro_viz/server.py", line 55, in <module>
    if KEDRO_VERSION.match(">=0.16.0"):
AttributeError: 'VersionInfo' object has no attribute 'match'
Error: Loading global commands from kedro-viz = kedro_viz.server:commands

Usage: kedro [OPTIONS] COMMAND [ARGS]...
Try 'kedro -h' for help.

Error: No such command 'viz'.

```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: chrome 
* Operating system and version: MAC OS
* Kedro version used (if relevant): 0.16.1
* Python version used (if relevant): 3.6.6
* Pyspark: 2.4.4

Thanks,

**Comment by 921kiyo** [comment]
Hi @zhangchi1 Could you run `pip install semver --upgrade`? We have fixed this issue in dev branch (but not released yet) https://github.com/quantumblacklabs/kedro-viz/pull/180

**Comment by zhangchi1** [comment]
Hi @921kiyo, thanks for the quick response. 

In addition, I'm using my own dataset, which is not stored under the `myproject/io/datasets/mydataset.py`. Basically, I created my own dataset as an external package so that I can easily use for other Kedro projects. However, I think currently, kedro-viz, by default, is looking for customized datasets under `myproject/io/datasets/mydataset...`. 

For example, under my `catalog.yml` file:
```
my_dataset:
      type: my_ext_package.datasets.my_dataset
      some_other_fields:
     ....
```

Do you know what would be the best way to modify the default location for customized datasets in kedro-viz? It would be nice to have this type of feature.

Thanks,

**Comment by 921kiyo** [comment]
Internally, Kedro tries to parse importable modules in 1. `kedro.io.XX`, 2. `kedro.extras.datasets.XX`, and 3. your custom import path. 1 and 2 are for build-in datasets (e.g https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras/datasets for 2) so as long as 3 is an importable module, it will parse it correctly. You can verify that with `importlib.import_module` https://docs.python.org/3/library/importlib.html

Hope this helps :)

**Comment by zhangchi1** [comment]
Thank you so much!
