### ISSUE TITLE
pass arguments with `run_viz` magic method

### ISSUE THREAD

**Issue by miyamonz** [quantumblacklabs/kedro-viz#263]
## Description
I just want to run `run_viz` with --host 0.0.0.0 option.

## Context
there is no auto-reload option. so just %reload_kedro and %run_viz in notebooks are very easy to see my visualized pipeline.

but I run kedro in a docker container in a remote server, so the host option should not be the default 127.0.0.1.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by miyamonz** [comment]
BTW, [CONTRIBUTING.md says](https://github.com/quantumblacklabs/kedro-viz/blob/main/CONTRIBUTING.md#suggest-a-new-feature) put label `Enhancement`, but I can't and automatically put `Feasture Request`. It's no problem, isn't it?

**Comment by 921kiyo** [comment]
Hi, am I correct that you want to know how to pass host args in your docker container? This is from Kedro-Docker, but does this instruction help? https://github.com/quantumblacklabs/kedro-docker#running-kedro-docker-with-kedro-viz

**Comment by miyamonz** [comment]
thanks! but is it any different than `docker exec {CONTAINER_NAME} kedro viz --host 0.0.0.0`?

Yes, just `docker exec` will works. I can pass any options.
It's a little pain to re-run the above command when I fix some code in a notebook.

**Comment by miyamonz** [comment]
Or maybe What I really want is auto-reload feature.

**Comment by 921kiyo** [comment]
Closing this, but if you would like to contribute the auto-reload feature, you are welcome to work on it in Kedro side :)
