### ISSUE TITLE
Hide  Params in pipeline diagram

### ISSUE THREAD

**Issue by clstaudt** [quantumblacklabs/kedro-viz#332]
## Description

Parameter data sets like parameters.yml are used to have global parameters that are used in many places defined in a single place, thereby avoiding redundancy.

This also means that a global parameters node is linked to many nodes in the data pipelines. This may make pipeline diagrams less readable. 

Please add the option to hide parameter nodes.

## Context

Improve readability of pipeline diagram.

**Comment by richardwestenra** [comment]
Hi @clstaudt, thanks for posting this issue! There is already a feature that allows you to hide all parameters: If you scroll down the sidebar to the list of parameters and hover over the Parameters title, you will see an 👁️ icon. If you click on this icon, it will toggle all parameters off, and they will stay disabled until you reenable them. Does this accomplish what you're looking for?
![image](https://user-images.githubusercontent.com/1155816/102082897-a7c17280-3e0a-11eb-9c7c-c8a3df7109cd.png) ![image](https://user-images.githubusercontent.com/1155816/102082930-b3149e00-3e0a-11eb-8185-2896456b124d.png)

Assuming it does, I am closing this issue, but please let me know if not and I will reopen it.

**Comment by clstaudt** [comment]
@richardwestenra  Thanks for pointing the feature out, somehow I missed it.
