### ISSUE TITLE
[KED-2555] Improve Error handling for missing parameters 

### ISSUE THREAD

**Issue by philippegr** [quantumblacklabs/kedro-viz#411]
## Description
My team ran twice into the same problem: we rely on some parameters that are not in any Kedro catalog.yaml so as to force the user to provide them via the cli (and `--params`). As a consequence kedro-viz can't infer their type and raises the following Error that is hard to link with the offending parameter(s). 
```
kedro_viz/server.py", line 427, in format_pipeline_data
    parameter_value = _get_dataset_data_params(namespace).load()
AttributeError: 'NoneType' object has no attribute 'load'
Error: 'NoneType' object has no attribute 'load'
```

## Possible Implementation
Catching the error to augment it with the name of the parameter that causes the issue.

## Possible Alternatives
(Optional) Providing a default handling for missing definitions? But I could understand that not specifying the parameter in any parameters.yaml is abusing the way Kedro works

**Comment by richardwestenra** [comment]
Thanks @philippegr! I've assigned this issue a JIRA ticket and we'll discuss prioritisation and possible implementations at the next backlog grooming.

**Comment by limdauto** [comment]
Hi @philippegr this should be improved now in viz 3.12.0!

We will still visualise the pipeline while displaying a warning in the CLI that the parameter is missing. We believe that missing parameter shouldn't block you from viewing the pipeline structure.
