### ISSUE TITLE
Incompatibility between Kedro 0.17.3 and Kedro-viz 3.11.0

### ISSUE THREAD

**Issue by gmartinonQM** [quantumblacklabs/kedro-viz#452]
## Description

Kedro-viz 3.11.0 try to call the method `_get_pipeline` of `KedroContext`, which does not exist anymore in Kedro 0.17.3.

## Context

Just trying to visualize a simple pipeline.

## Steps to Reproduce

1. create a pipeline
2. run the pipeline with `kedro run`
3. visualize the pipeline with `kedro viz`

## Expected Result

Expect my browser to open with a pipelien visualization.

## Actual Result

Here is the error I get. The pipeline run successfully. The visualization crashes.

```
Traceback (most recent call last):
  File "/home/ec2-user/.local/share/virtualenvs/api-dyJrA_NI/lib/python3.8/site-packages/kedro_viz/server.py", line 755, in viz
    _call_viz(host, port, browser, load_file, save_file, pipeline, env)
  File "/home/ec2-user/.local/share/virtualenvs/api-dyJrA_NI/lib/python3.8/site-packages/kedro_viz/server.py", line 808, in _call_viz
    pipelines = _get_pipelines_from_context(context, pipeline_name)
  File "/home/ec2-user/.local/share/virtualenvs/api-dyJrA_NI/lib/python3.8/site-packages/kedro_viz/server.py", line 183, in _get_pipelines_from_context
    return {pipeline_name: context._get_pipeline(name=pipeline_name)}
AttributeError: 'KedroContext' object has no attribute '_get_pipeline'
kedro.framework.cli.utils.KedroCliError: 'KedroContext' object has no attribute '_get_pipeline'
```

## Your Environment

* Operating system and version: AWS Cloud9 (EC2 instance, RedHat)
* Kedro version used : 0.17.3
* Kedro-viz version used : 3.11.0
* Python version used : 3.8.7

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by limdauto** [comment]
Hi @gmartinonQM thank you for reporting this. This should be fixed now in viz 3.12.0!
