### ISSUE TITLE
[KED-2720]`--to-inputs` instead of `--to-outputs` and prettified names in panel "run command" suggestion

### ISSUE THREAD

**Issue by martinsotir** [quantumblacklabs/kedro-viz#492]
## Description

The `Run Command` information in node panels is invalid or outdated for some use-cases :

1. For datasets, the panel shows `kedro run --to-inputs` instead of `kedro run --to-outputs` (or `kedro run --from-inputs`).

2. If a node does not have an explicit name, the generated command line will contain a prettified node name that will not work (ex: `kedro run --to-nodes Process Items `, for a function `process_items()`). If it is not possible to reference an unnamed node by the command line, maybe a message could be shown in place of the command in the kedro-viz panel?

3. A suggestion: For node, it would be practical to show both the `kedro run --to-nodes <name>` and `kedro run --node <name>` commands (helps in the discovery of `kedro run` options)

## Steps to Reproduce

Those issues should occur with any kedro pipeline (with at least one unnamed node for the second issue).

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version:
* NodeJS version used (if relevant):
* Kedro version used (if relevant):
* Python version used (if relevant):

## Your Environment

* Kedro-viz version: 3.12.1
* Web browser system and version: Chrome 91
* Operating system and version: Linux
* Kedro version used: 0.17.4
* Python version used: 3.8

**Comment by limdauto** [comment]
Hi @martinsotir this is now fixed in latest Kedro viz.
