### ISSUE TITLE
Kedro Viz load-file not working

### ISSUE THREAD

**Issue by WaterKnight1998** [quantumblacklabs/kedro-viz#509]
## Description
`kedro viz --load-file` not working properly

## Context
How has this bug affected you? What were you trying to accomplish?

I want to save Kedro Viz into a json and load from it, as shown in Kedro [documentation](https://kedro.readthedocs.io/en/stable/03_tutorial/06_visualise_pipeline.html#share-a-pipeline).

## Steps to Reproduce

1. `kedro viz --save-file my_shareable_pipeline.json`
2. `kedro viz --load-file my_shareable_pipeline.json`

## Expected Result
Website rendering pipeline

## Actual Result
Error website with this content:
```
{"detail":"Not Found"}
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: 
* Operating system and version: Windows 10
* Kedro version used (if relevant):
   kedro~=0.17.4
   kedro-viz==3.13.0
* Python version used (if relevant):  3.7.10

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by limdauto** [comment]
@WaterKnight1998 This is now fixed in `kedro-viz==3.13.1`. Please upgrade and try it out. Let me know if you still have problems.

**Comment by WaterKnight1998** [comment]
@limdauto it's working now. Thank you very much! You solve it so fast!
