### ISSUE TITLE
Export graph from Python

### ISSUE THREAD

**Issue by WaterKnight1998** [quantumblacklabs/kedro-viz#513]
## Description
I would like to have a function that receives an Instance of a Kedro Pipeline and exports it as PNG.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?
I will use it from a Notebook to visualize my pipeline object into the same cell. So there is no need to open ports to visualise the pipeline.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by yetudada** [comment]
Hi @WaterKnight1998! Thanks for raising this. This functionality is already possible in a [Jupyter notebook](https://kedro.readthedocs.io/en/stable/11_tools_integration/02_ipython.html#kedro-viz-and-jupyter). This should solve what you're trying to do and therefore I'll close this issue. Just comment if we need to re-open this issue for more investigation.

**Comment by WaterKnight1998** [comment]
> Hi @WaterKnight1998! Thanks for raising this. This functionality is already possible in a [Jupyter notebook](https://kedro.readthedocs.io/en/stable/11_tools_integration/02_ipython.html#kedro-viz-and-jupyter). This should solve what you're trying to do and therefore I'll close this issue. Just comment if we need to re-open this issue for more investigation.

@yetudada Thank you for answering. 

The use case is:
I have created the pipeline object without Kedro's project structure. Just create Pipeline object and running it passing directly to Runner object.

I would like to have a python function that receives the pipeline object and creates a png. Not a Jupyter Widget that returns an iframe pointing to the Kedro-Viz server that was started in background.
