### ISSUE TITLE
Investigating a new API integration layer for Kedro-viz

### ISSUE THREAD

**Issue by studioswong** [quantumblacklabs/kedro-viz#560]
## Introduction

This document aims to provide a very high level overview and discussion of the possible options for the FE architecture to enable the work for experiment tracking milestone 2. ( refer to [this document](https://github.com/quantumblacklabs/private-kedro/issues/1192#issuecomment-896138408) for a previous discussion on this milestone.)

## Background

In this milestone, on Kedro-Viz, we will display:

- A list of previous runs of a Kedro project.
- When users click on a particular run, they can see an aggregation of all tracked data (metrics and JSON) in the run.

There are 3 main requirements to enable the above: 

**Requirement 1**
The ability to list a historical list of runs data 

**Requirement 2**
Real time updates of run list data 

**Requirement 3**
Fast load times of a potentially vast amount of runs list data 

Some background information about our setup:
- There is no websocket setup on the kedro-viz server
- As outlined by @limdauto in the technical design, there is currently no persistent session store on Kedro core 
- The FE data fetching and state management is set up and managed  in Redux
- The existing server provides 3 REST endpoints (`/api/main`, `/api/nodes/<id>`, `/api/pipeline/<id>` )

Please refer below to a very high level overview of the existing set up of the data flow between the FE and the Kedro-viz server. 

![API integration layer - existing setup](https://user-images.githubusercontent.com/27775658/133523931-5025c9fc-509c-453b-b2a4-d19105415ad4.jpg)

## Challenges

- Lack of a setup  to enable real time communication between the FE cilent and the server (i.e. webhooks / websockets)
- Integrating web sockets within the existing Redux architecture and events requires complex setup and configuration work
- The vast amount of runs data suggests the need to optimize data load times. 

## Proposal

With the above requirements and challenges, The goal of this study is to find an easy and effective solution for web socket integration and caching within our app. 

My proposal works alongside the following assumptions:

_**On the Core side:**_
- As proposed by @limdauto in the previous discussion, a persistent session store will be created to store and host session data for each run

_**On the kedro-viz server side:**_
- Websockets(or webhooks) should be set up on the Kedro-viz server to enable real time communication. While the FE client can still set up polling to continuously fetch new information from the server, it is however an expensive and highly inefficient endeavour to constantly poll the backend for the session data.

### API integration
On having implemented web-sockets, one of the biggest challenges on the FE is the integration and management of the web socket connection, which is often an enormous task of configuration. This is when introducing GraphQL as an API integration layer comes in as a great setup for this transition. 

The following diagram summarises and outlines the overall requirements and the related proposed technologies that will be discussed below. 

![API integration layer - Kedro-viz](https://user-images.githubusercontent.com/27775658/133487092-6be9f27b-5e0f-4edb-b8c0-33102890f64d.jpg)

**GraphQL**
To enable the real time update of the session data (requirement 2), I propose utilising the [GraphQL](https://graphql.org/) technology as an API integration layer to enable real time communication via GraphQL subscriptions. GraphQL is a query language for APIs that allows the execution of queries using a type system / schema. It support three types of operations: Queries for data fetching, Mutations for data writing, and Subscriptions for active data pushing from the server on updates ( which requires a web-socket connection). 

There are 3 main reasons I propose GraphQL as an API integration layer:
- GraphQL subscriptions provides a quick and easy means with minimal setup for seamless web socket integration to obtain real time data 
- the ability to query the backend via structured queries tailored to the data structure of the runs list data
- The ability to set up pagination for our response would work well for cases of an extensive list of runslist data to enable lazy loading 

### Caching
To allow fast load times for potential large lists of runs data, I propose setting up a cache infrastructure within the FE app to minimise the amount of data to be fetched on each query. This can be done via setting up a FE client that comes with a built in cache to store queried data for state management within the app. 

The following are a list of libraries that provides a FE client with in built caching solution:

 **[Apollo Client ](https://www.apollographql.com/docs/react/)(GraphQL only)**
Apollo client for React is the most commonly used state management library to manage and organize local and remote data for GraphQL within a FE application. It allows declarative data fetching and writing ( via GraphQL queries, mutations and subscriptions), while providing a normalised cache in storing data locally for optimising network requests. 

_PROS_: 
- minimal effort for setting up graphQL operations that works seamlessly with its inbuilt zero-config cache
- Subscriptions to an endpoint are set up by default within their `useQuery` methods, as long as a web-socket connection is available for endpoint, meaning minimal effort to get our real time connection setup
- The vibrant ecosystem around Apollo pretty much means we can find a related solution for most scenerios. 

_CONS_: 
- Given Apollo's focus on the easy integration of the cache, this also implies that custom configuration of the inbuilt Apollo cache to tailor for our specific data and state management needs might not be very straight forward. 

 **[URQL](https://formidable.com/open-source/urql/docs/) + [GraphCache](https://formidable.com/open-source/urql/docs/graphcache/) (GraphQL only)**

URQL is another GraphQL client that adopts a very similar syntax with Apollo for its graphQL operations, yet takes a more customizable approach rather than Apollo's more generic approach, especially towards data caching. 

The main difference between URQL and Apollo is that URQL uses the document-based cache by default, with the option of adopting a normalized cache (GraphCache). ( in short, Document caching works well for content heavy single pages, while a normalized cache will handle more dynamic and heavy data intensive apps that is more suited for state management.)

_PROS_:  
- A more lightweight FE client that allows more flexibility and extensibility for customisation as we scale the extent of GraphQL within our app.
- While it is a newcomer as a GraphQL client, the maintainers are highly motivated in growing their community, where issues gets resolved very quickly, with the team highly motivated in supporting additional functionality, such as offline mode and integration with Next.js. Their docs are also very extensive with very clear guidelines for setting up "exchanges" for different needs. 
- The extra choice to adopt a simpler document cache rather than a normalized cache might work better in our case given the complexity behind managing a normalized cache. 

_CONS_: 
- a highly customisable and lightweight approach is a double-edged sword - while we have the flexibility for workaround to create custom solutions, it also likely meant further efforts to deep dive and understand URQL's "exchanges" in order to form the right solution for our needs. 

The main decision between the adoption of Apollo vs URQL comes down to the preference of our cache. While Apollo provides an extremely easy 'plug and play' approach with a highly functional normalised cache, we might come across problems in customising the cache for our unique state management needs down the line when we migrate our app for our state management to fully rely on the cache. While URQL might requires more setup and customisation work, the flexibility and extensibility it allows meant that we could adopt to whichever specific needs we might come across as the experiment tracking features evolve down the line. 

**[React Query](https://react-query.tanstack.com/) (GraphQL and REST)**

React Query is an opinionated data fetching library that takes the simplicity towards data fetching adopted by Apollo towards REST endpoints, including providing a default cache to enable easy server state management. Similar to Apollo client for react, It provides a set of React hooks for data fetching, yet it takes in callbacks in the form of promises / async functions hence allowing the flexibility to fetch data from a REST endpoint. 

_PROS:_ 
- The flexibility to work with REST and GraphQL means minimal changes on the FE shall the BE decides to continue with the existing setup of a REST endpoint. In the case of a hybrid situation of the existence of both REST and GraphQL endpoints, adopting React Query will allow a unified approach towards data fetching on the FE codebase. 

_CONS:_ 
- While it adopts a similar mindset as Apollo for queries and mutations, it does not provide any built in support for subscriptions, meaning that extra efforts is required to integrate with web sockets to enable real time data connection. 
- There aren't any transparency behind the mechanism of their caching logic, as well as docs for customisation of their cache, which might imply the lack of flexibility to extend beyond the current setup of their cache. 
- The lack of a normalised cache implies that their cache cannot be used to handle dynamic state management for the entire app ( which is default by design, as it is only designed to handle server data cache) 

**[RTK Query](https://redux-toolkit.js.org/rtk-query/overview) (GraphQL and REST)**

RTK Query is a data fetching and caching tool designed specifically for usage alongside Redux. Similar to React Query, it has taken inspiration from Apollo and other GraphQL in their simplicity towards data fetching, at the same time providing caching capability. Most importantly, it also provides the ability to receive streaming updates for persistent queries (i.e integration with web-sockets) within the redux framework, which takes away a lot of the potential challenges in the complex setup work shall we were to use an external library such as socket.io. 

_PROS:_ 
- With it specifically designed to work alongside Redux architecture, adopting RTK Query pretty much means the continuation of our existing development mindset with Redux.  I especially like that the query setup ( which in RTK terms, is created via the `createAPI` service) hooks directly into the Redux store, hence allowing us to continue the adoption of the redux store for state management. 

_CONS:_
- being a recent addition into the redux library, there is not much community support for this library
- While it has simplfied the setup of the cache, it is still _**very**_ complicated to setup RTK query before it can be be utilised for data fetching within our app. 
- Similar to React Query, it does not provide a normalised cache ( though this might not be a problem given the handling of app state will still be handled by Redux)
- The lack of docs for the configuration of the cache implies limitations in its flexibility 

Having evaluated through the list of possible options, I believe the implementation of GraphQL as an integration layer is the right solution for us given its simplicity in setting up real time data connection with GraphQL subscriptions.  Given the vast amount of data fields associated with a runslist response, the ability to format our data fetching and responses via structured queries in tying to the data needs of our component will greatly help with simplifying the management and future maintenance of that feature. 

In terms of the FE client, I would recommend for us to start with Apollo given the minimal amount of setup work required, which will help us set the groundwork in seamlessly integrate GraphQL into our FE codebase. While URQL is definitely a great choice, and most likely a more preferable choice down the line given its extensibility and flexibility, Apollo is a better choice for us to obtain quick wins in building the first iteration of the experiment tracking features. We could revisit the client choice once we hit the stage that requires a more customised cache, which by then a migration would not be hard, given the similarties in syntax between the two libraries. 

Below is a brief summary of the possible combinations of the above techcnology in relation to the efforts required and values it brings.

![API integration layer - comparison](https://user-images.githubusercontent.com/27775658/133772982-beb44c2f-321b-48bc-91e7-573051179afc.jpg)

## Technical Design

Implementation of GraphQL as an API integration layer

**GraphQL integration** 

GraphQL + FE Client ( Apollo / URQL) + web-sockets

![API integration layer - graphql with websockets](https://user-images.githubusercontent.com/27775658/133515322-274dc15c-831f-402e-91aa-cab0134fafc2.jpg)

GraphQL + FE Client ( Apollo / URQL) + polling

In the event that websockets are not supported, we can still constant updates via polling ( which will be set up under GraphQL queries.) However, polling is highly inefficient given the extensive and unneccessary amount of requests ( while failing to utilize the beauty and ease of GraphQL subscriptions), and should not be considered unless the implementation of websockets is not an option. 

![API integration layer - graphql with polling](https://user-images.githubusercontent.com/27775658/133515337-74e227bd-2cb2-4ca1-9ecc-77ee94ce8fa5.jpg)

### Alternatives considered

RTK Query + REST +  Redux
 Data fetching will be managed by RTK query, while state management will still be maintained by the redux store.  

React Query + REST + ContextAPI 

React Query will handle all data fetching, caching and state management of all server side data, while all app state can either be managed via state hooks, or in a more complex case, via the ContextAPI. 

## Rollout strategy

Given that the migration towards GraphQL will have huge implications for all part of the app ( from state management down to mechanisms for data fetching), the fresh start of the runslist feature provides the perfect opportunity to build out this newly proposed FE architecture. 

**Stage 0: Setup of the GraphQL layer with Apollo client**
This is the stage where we laid the foundational work in setting up the GraphQL layer ( schemas and resolvers) between the REST API and the FE app. 

Kedro-Viz server:  Setting up a GraphQL layer to serve the runslist data

Related tasks:
- Pre-requisite: Setting up web-sockets for the Kedro-viz server
- Pre-requisite: Setting up persistent session store to store and host runslist data ( enabled by the Kedro-core team)
- Set up of the runslist endpoint on the REST server. 
- Boilerplate code setup for GraphQL infrastructure
- Set up of related schema and resolvers for the runslist endpoint ( to liase with Kedro-viz team members to agree on the response data structure)

Kedro-viz FE: Set up of GraphQL Client and its integration with the GraphQL endpoint
This can be done simultaneously alongside  the BE work in setting up the new GraphQL endpoint for the runslist data

Related tasks:
- Set up a graphQL mock for mocking responses for the runslist endpoint 
- Set up of Apollo client on the FE codebase, and in particular, spike and configure the apollo cache
- Test the setup and the response to the FE with the graphQL mock
- Setup new data mocks within tests to match the new GraphQL responses
- Once the GraphQL endpoint is implemented on the server, help with testing of the responses of the new endpoint ( which can be done first via Graphiql )

By the end of this stage, the app will be in a "hybrid" state in terms of data fetching, where the existing endpoints will still follow the REST protocol, while the setup of the GraphQL infrastructure for the new runslist endpoint provides the perfect setup to build the new features with speed. This is made possible given that the new experiment tracking UI will be available as a separate route ( there will be a further spike on the routing stategy ), allowing us to create a clear seperation of concerns within the codebase. 

Please refer to below diagram for a very brief overview of the proposed rollout sequence:

![API integration layer - rollout sequence](https://user-images.githubusercontent.com/27775658/133772344-e84d78e8-4d93-4c81-9545-8b3c37e1ddb5.jpg)

**Stage 1: Building the Experiment tracking UI ( detailed tasks TBD with the final design)** 

**Stage 2: Gradual migration of existing endpoints and FE codebase to GraphQL; elimination of Redux setup**
Once the setup of our GraphQL infrastructure reaches maturity as it is battle tested with the shipping of the experiment tracking features, we can also start to revisit the other remaining REST endpoints, as well as other main components of the FE app, to slowly migrate towards the 'GraphQL' way in stripping away the complexity of the existing redux setup.

**Comment by limdauto** [comment]
Thanks @studioswong it's safe to say with the rollout of exp tracking v1 and soon v2, this was a success. Closing this design doc as a result.
