### ISSUE TITLE
Add Ability to pass pipeline into get_data_from_kedro

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro-viz#69]
## Description
I would like to have the ability to create kedro-viz data and save it to a json file outside of running the kedro-viz server.  The main motivation for this is to keep a simple live version of every pipeline my team is maintaining right at our fingertips for anyone to view.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation

https://github.com/quantumblacklabs/kedro-viz/blob/develop/package/kedro_viz/server.py#L110

``` diff
- def get_data_from_kedro():
+ def get_data_from_kedro(pipeline=None):
    """ Get pipeline data from Kedro and format it appropriately """

    def pretty_name(name):
        name = name.replace("-", " ").replace("_", " ")
        parts = [n[0].upper() + n[1:] for n in name.split()]
        return " ".join(parts)

-     pipeline = get_project_context("create_pipeline")()
+    if pipeline == None:
+       pipeline = get_project_context("create_pipeline")()
```

I looked at making this change but do not understand how `kedro-viz` gets packaged.  I tried to inspect kedro.server, but do not even see `get_data_from_kedro`

## Possible Alternatives

Copy the `get_data_from_kedro` function into my own codebase and make the change myself.  I have done this, but do not want to maintain a "fork" of this function so that we can easily follow any data structure changes.

## Checklist

- [x] Include labels so that we can categorise your feature request
- [x] Make `get_data_from_kedro` importable
- [x] Allow pipeline data to be passed into `get_data_from_kedro`

**Comment by tolomea** [comment]
get_data_from_kedro was added since the latest release and will be in the next release which is due relatively soon.
That release will also add `--save-file` and `--load-file` arguments to `kedro viz` might those cover your needs?

**Comment by tolomea** [comment]
also it's worth noting that the data format is changing a bit in the next version, which is why you have experienced problems with the get_data_from_kedro function, it's deigned for the new data format

**Comment by WaylonWalker** [comment]
@tolomea That makes sense why it seemed so different from my installed version.  I would really like the ability to generate this data from python without needing to find the directory of the project and run the cli command, as I already have the pipeline object in memory.  I submitted a PR for you to consider this change.
