### ISSUE TITLE
Built-in way to viz non-default pipelines.

### ISSUE THREAD

**Issue by jonasrk** [quantumblacklabs/kedro-viz#97]
There currently does not seem to exist a built-in way to viz non-default pipelines.

The current work-around is to change the default pipeline in the kedro project code.

It would be great to viz alternative pipelines without touching code.

**Comment by 921kiyo** [comment]
@jonasrk Thank you for the feature request! I'm actually working on it in https://github.com/quantumblacklabs/kedro-viz/pull/93 and it will be available in the next release :)

**Comment by 921kiyo** [comment]
It is implemeted in https://github.com/quantumblacklabs/kedro-viz/pull/93, so I'm closing this :)
